/**
 * ────────────────────────────────────────────────────────────────────────────
 *  generate-sitemap.mjs  —  build-time XML sitemap generator
 * ────────────────────────────────────────────────────────────────────────────
 *  Reads the Angular Router config (src/app/app.routes.ts) as the SINGLE source
 *  of truth, then writes public/sitemap.xml with <loc>, <lastmod>, <changefreq>
 *  and <priority> for every public page.
 *
 *  Run automatically before every build via the "prebuild" npm hook, so the
 *  sitemap can never drift out of sync with the routes. Add a route → rebuild →
 *  the sitemap updates itself. No manual editing required.
 *
 *  Usage:  node scripts/generate-sitemap.mjs
 * ────────────────────────────────────────────────────────────────────────────
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const SITE_URL = 'https://bhagavadkarma.org';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ROUTES_FILE = resolve(ROOT, 'src/app/app.routes.ts');
const OUTPUT_FILE = resolve(ROOT, 'public/sitemap.xml');

/** Concrete values to substitute for parameterised routes (e.g. :category). */
const PARAM_SUBSTITUTIONS = {
  'store/:category': ['store/skincare'],
};

/** Per-path crawl hints. Falls back to DEFAULT_HINT for anything unlisted. */
const HINTS = {
  '': { changefreq: 'weekly', priority: '1.0' },
  contact: { changefreq: 'monthly', priority: '0.9' },
  appointment: { changefreq: 'monthly', priority: '0.9' },
  donation: { changefreq: 'monthly', priority: '0.9' },
  member: { changefreq: 'monthly', priority: '0.8' },
  news: { changefreq: 'weekly', priority: '0.8' },
  'who-we-are': { changefreq: 'monthly', priority: '0.8' },
  'our-guru': { changefreq: 'monthly', priority: '0.8' },
  'store/skincare': { changefreq: 'weekly', priority: '0.7' },
  allproducts: { changefreq: 'weekly', priority: '0.7' },
};
const DEFAULT_HINT = { changefreq: 'monthly', priority: '0.7' };

/**
 * Pull every path:'...' literal out of the routes file — but SKIP lines that
 * declare a redirect (backward-compatible old→new URL aliases). Redirect URLs
 * must not appear in the sitemap; only their canonical targets should.
 */
function extractPaths(source) {
  const found = new Set();
  for (const line of source.split('\n')) {
    if (/redirectTo/.test(line)) continue; // skip backward-compat redirects
    const m = /path\s*:\s*['"]([^'"]*)['"]/.exec(line);
    if (m) found.add(m[1]);
  }
  return [...found];
}

/** Turn raw route paths into a clean, deduped list of public URL paths. */
function toUrlPaths(rawPaths) {
  const urls = new Set();
  for (const p of rawPaths) {
    if (p === '**') continue; // wildcard / not-found
    if (p === 'home') continue; // duplicate of '' (home) — keep one canonical
    if (p.includes(':')) {
      // Parameterised — expand with known concrete values, skip if none.
      for (const sub of PARAM_SUBSTITUTIONS[p] ?? []) urls.add(sub);
      continue;
    }
    urls.add(p); // '' stays as the homepage
  }
  return [...urls];
}

function buildXml(urlPaths, lastmod) {
  const ordered = urlPaths.sort((a, b) => {
    const pa = Number((HINTS[a] ?? DEFAULT_HINT).priority);
    const pb = Number((HINTS[b] ?? DEFAULT_HINT).priority);
    return pb - pa || a.localeCompare(b);
  });

  const entries = ordered
    .map((path) => {
      const hint = HINTS[path] ?? DEFAULT_HINT;
      const loc = path === '' ? `${SITE_URL}/` : `${SITE_URL}/${path}`;
      return [
        '  <url>',
        `    <loc>${loc}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${hint.changefreq}</changefreq>`,
        `    <priority>${hint.priority}</priority>`,
        '  </url>',
      ].join('\n');
    })
    .join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Auto-generated by scripts/generate-sitemap.mjs — do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries,
    '</urlset>',
    '',
  ].join('\n');
}

function main() {
  const source = readFileSync(ROUTES_FILE, 'utf8');
  const urlPaths = toUrlPaths(extractPaths(source));
  const lastmod = new Date().toISOString().split('T')[0];
  const xml = buildXml(urlPaths, lastmod);
  writeFileSync(OUTPUT_FILE, xml, 'utf8');
  console.log(
    `✓ sitemap.xml generated with ${urlPaths.length} URLs → ${OUTPUT_FILE}`
  );
}

main();
